name: ${pluginName}
version: ${version}
main: com.willfp.ecopets.EcoPetsPlugin
api-version: 1.17
authors: [ Auxilor ]
website: willfp.com
depend:
  - eco
softdepend:
  - libreforge
commands:
  ecopets:
    description: Base Command
    permission: ecopets.command.ecopets
  pets:
    aliases:
      - pet
    description: Open the pets menu
    permission: ecopets.command.pets
    default: true

permissions:
  ecopets.*:
    description: All ecopets permissions
    default: op
    children:
      ecopets.command.*: true
  ecopets.command.*:
    description: All commands
    default: op
    children:
      ecopets.command.ecopets: true
      ecopets.command.reload: true
      ecopets.command.pets: true
      ecopets.command.give: true
      ecopets.command.giveegg: true
      ecopets.command.givexp: true
      ecopets.command.givecurrentxp: true
      ecopets.command.reset: true
      ecopets.command.activate: true
      ecopets.command.deactivate: true

  ecopets.command.reload:
    description: Allows reloading the config
    default: op
  ecopets.command.ecopets:
    description: Allows the use of /ecopets.
    default: true
  ecopets.command.pets:
    description: Allows the use of /pets.
    default: true
  ecopets.command.give:
    description: Allows the use of /ecopets give.
    default: op
  ecopets.command.giveegg:
    description: Allows the use of /ecopets giveegg.
    default: op
  ecopets.command.givexp:
    description: Allows the use of /ecopets givexp.
    default: op
  ecopets.command.givecurrentxp:
    description: Allows the use of /ecopets givecurrentxp.
    default: op
  ecopets.command.reset:
    description: Allows the use of /ecopets reset.
    default: op
  ecopets.command.activate:
    description: Allows the use of /pets activate.
    default: true
  ecopets.command.deactivate:
    description: Allows the use of /pets deactivate.
    default: true

  ecopets.xpmultiplier.50percent:
    description: Gives the player 50% more skill experience
    default: false
  ecopets.xpmultiplier.double:
    description: Gives the player 2x skill experience
    default: false
  ecopets.xpmultiplier.triple:
    description: Gives the player 3x skill experience
    default: false
  ecopets.xpmultiplier.quadruple:
    description: Gives the player 4x skill experience
    default: false
